-- Add inline comments explaining key fields
CREATE TABLE combined_customer_data (
  customerID VARCHAR(50) PRIMARY KEY,
  gender VARCHAR(10),
  SeniorCitizen TINYINT,
  Partner TINYINT,
  Dependents TINYINT,
  tenure INT,
  PhoneService VARCHAR(10),
  MultipleLines VARCHAR(20),
  InternetService VARCHAR(20),
  OnlineSecurity VARCHAR(20),
  OnlineBackup VARCHAR(20),
  DeviceProtection VARCHAR(20),
  TechSupport VARCHAR(20),
  StreamingTV VARCHAR(20),
  StreamingMovies VARCHAR(20),
  Contract VARCHAR(30),
  PaperlessBilling TINYINT,
  PaymentMethod VARCHAR(50),
  MonthlyCharges DECIMAL(9,2),
  TotalCharges DECIMAL(12,2),
  Churn TINYINT,
  tenure_group VARCHAR(30),
  is_new_customer TINYINT,
  is_long_term TINYINT,
  total_revenue DECIMAL(12,2),
  charge_category VARCHAR(20),
  charge_ratio DECIMAL(9,6),
  num_services TINYINT,
  is_monthly_contract TINYINT,
  paperless_billing_binary TINYINT,
  family_size TINYINT
);
 
